from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'supporter'
urlpatterns = [
    path('', views.Login.as_view(), name = 'Login'),
    path('Login/LoginProf', views.LoginProf.as_view(), name = 'LoginProf'),
    path('Login/LoginStud', views.LoginStud.as_view(), name = 'LoginStud'),
    path('Login/LoginAdmin', views.LoginAdmin.as_view(), name = 'LoginAdmin'),
    path('Login/Check/', views.Check, name = 'Check'),
    path('Login/Check2/', views.Check2, name = 'Check2'),
    path('Login/Check3/', views.Check3, name = 'Check3'),
    path('Login/ProfMemb/', views.ProfMemb.as_view(), name = 'ProfMemb'),
    path('Login/StudMemb/', views.StudMemb.as_view(), name = 'StudMemb'),
    path('Prof/<int:professor_id>/', views.ProfUser.as_view(), name='ProfUser'),
    path('Prof/<int:professor_id>/Info/', views.ProfUserinfo.as_view(), name='ProfInfo'),
    path('Prof/<int:professor_id>/AddLec/', views.AddLecP.as_view(), name='AddLecP'),
    path('Prof/<int:professor_id>/<int:lecture_id>/', views.LecInfo.as_view(), name='LecInfo'),
    path('Prof/<int:professor_id>/<int:lecture_id>/Change/', views.ProflectureChange.as_view(), name='LecChange'),
    path('Prof/<int:professor_id>/<int:lecture_id>/lecdele/', views.dele, name = 'lecdeld'),
    path('Prof/<int:professor_id>/<int:lecture_id>/AttendBook/', views.AttendBook.as_view(), name='AttendBook'),
    path('Prof/<int:professor_id>/<int:lecture_id>/AddBoard/', views.AddBoard.as_view(), name='AddBoard'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/', views.BoardList.as_view(), name='BoardList'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/', views.BoardInfo.as_view(), name='BoardInfo'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/Change/', views.ProfBoardChange.as_view(), name='BoardChange'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/BoardDel/', views.BoardDel, name = 'BoardDel'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/AddReply/', views.AddReply, name='AddReply'),
    path('Prof/<int:professor_id>/<int:lecture_id>/BoardList/<int:board_id>/<int:reply_id>/ReplyDel/', views.ReplyDel, name='ReplyDel'),
    path('Prof/<int:professor_id>/<int:lecture_id>/AddReport/', views.AddReport.as_view(), name='AddReport'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/', views.ReportList.as_view(), name='ReportList'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/', views.ReportInfo.as_view(), name='ReportInfo'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/Change/', views.ProfReportChange.as_view(), name='ReportChange'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/ReportDel/', views.ReportDel, name = 'ReportDel'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/AddReply/', views.AddRepoReply, name='AddRepoReply'),
    path('Prof/<int:professor_id>/<int:lecture_id>/ReportList/<int:report_id>/<int:reply_id>/ReplyDel/', views.RepoReplyDel, name='RepoReplyDel'),
    path('Stud/<int:student_id>/', views.StudUser.as_view(), name='StudUser'),
    path('Stud/<int:student_id>/Info/', views.StudUserinfo.as_view(), name='StudInfo'),
    path('Stud/<int:student_id>/application/', views.LecList.as_view(), name = 'leclist'),
    path('Stud/<int:student_id>/application/<int:lecture_id>/', views.StudApplication.as_view(), name = 'application'),
    path('Stud/<int:student_id>/application/<int:lecture_id>/Check/', views.LecCheck.as_view(), name = 'lecCheck'),
    path('Stud/<int:student_id>/<int:lecture_id>/', views.StudLecInfo.as_view(), name='StudLecInfo'),
    path('Stud/<int:student_id>/<int:lecture_id>/BoardList/', views.BoardListStud.as_view(), name='BoardListStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/BoardList/<int:board_id>/', views.BoardInfoStud.as_view(), name='BoardInfoStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/BoardList/<int:board_id>/AddReply/', views.AddReplyStud, name='AddReplyStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/BoardList/<int:board_id>/<int:reply_id>/ReplyDel/', views.ReplyStudDel, name='ReplyStudDel'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/', views.ReportListStud.as_view(), name='ReportListStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/', views.ReportInfoStud.as_view(), name='ReportInfoStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/AddReply/', views.AddRepoReplyStud, name='AddRepoReplyStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/ReportManagStud/', views.ReportManagStud.as_view(), name='ReportManagStud'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/ReportDel/', views.Report_StudDel, name='Report_StudDel'),
    path('Stud/<int:student_id>/<int:lecture_id>/ReportList/<int:report_id>/<int:reply_id>/ReplyDel/', views.RepoReplyStudDel, name='RepoReplyStudDel'),
    ] 